version: "3.0"

services:
  app:
    image:  zethuman/zooshop:latest
    ports:
      - 3000:3000
    environment:
      AZURE_STORAGE_CONNECTION_STRING: oHYs4OjNK1vu7CGn8VkDkqJCFD+U8xVzmR0jl23xCAH4K5FlHJBQeDDqwgB36W6HBE92kbgoLaFzkpE/W6rrIQ==
      COSMOS_ENDPOINT: https://zooshopdatastorage.documents.azure.com:443/
      COSMOS_KEY: LmcUs0eULPDsf0NyyhhAqoLElVkcwqKL5iTSB5RhO2R1XjzCtcMUHd8lQn0QiHNlUnlzDOL6kTjb58uC083RqA==
      COSMOS_DATABASE_ID: zooshopdb
      COSMOS_CONTAINER_ID: zooshopcontainer